### ISSUE TITLE
distribution request

### ISSUE THREAD

**Issue by archey** [chokepoint/Beleth#2]
I am a developer for blackarch.org and we are building a pentest repo for archlinux users. We would like to include your tool in our repo, I only ask because I do not see a license file associated with this tool. Please let us know if its OK to use your tool.

**Comment by chokepoint** [comment]
Sure thing, go ahead and add it. If you need any help with the distro let me know. I built a few custom live boot Arch pen testing CDs back in the day. Thanks for the interest.

**Comment by archey** [comment]
Thanks for approval, if you want to help out feel free to make a pull request. Here is the issue list:
https://github.com/BlackArch/blackarch/issues?direction=desc&page=2&sort=updated&state=open

**Comment by archey** [comment]
Please feel free to add feature requests and packages on the todolist
